DockerApiException: Docker API responded with status code=InternalServerError, 
response={"message":"oci runtime error: 
container_linux.go:265: starting container process caused 
\"exec: \\\"[\\\\\\\"/bin/bash\\\\\\\", \\\\\\\"-c\\\\\\\", \\\\\\\"gams model.gms gdx=output\\\\\\\"]\\\": stat [\\\"/bin/bash\\\", \\\"-c\\\", \\\"gams model.gms gdx=output\\\"]: no such file or directory\"\n"}
